### ISSUE TITLE
check ivs and evs don't work

### ISSUE THREAD

**Issue by Darkzyber** [EverNife/BukkitPixelmonPlaceholders#2]
![image](https://user-images.githubusercontent.com/49058689/195727359-68a8894f-43a7-4c4b-8e8d-7fadee03b937.png)

**Comment by Darkzyber** [comment]
![image](https://user-images.githubusercontent.com/49058689/195727614-0d1b5fc5-af46-4b8e-8bd9-938652ef5658.png)
some papi is work but iv ,ev and can_gmax  is show %<iv,ev,can>%

**Comment by EverNife** [comment]
I will fix it, ty

**Comment by EverNife** [comment]
Fixed at https://github.com/EverNife/BukkitPixelmonPlaceholders/commit/2c1002040863b4dc9ec2aba80310cbb26118729a
